FROM node:16-alpine

# workdir is /app directory to avoid any conflicts
WORKDIR '/app'

# For the "COPY" command, this copies everything in package.json to the current WORKDIR folder '.'

COPY ./package.json ./

# Install all the dependencies of package.json
RUN npm install

# COPY command copies all of our src code into our WORKDIR - a temporary container created during the image building process
COPY . .

# this sets the default startup command to be 'npm run start' when we run the container
CMD ["npm", "run", "start"]